Update GID due to gCloud conflict with group tests

diff --git a/tests/p_shadow-utils/34-groupmod_tests b/tests/p_shadow-utils/34-groupmod_tests
--- a/tests/p_shadow-utils/34-groupmod_tests
+++ b/tests/p_shadow-utils/34-groupmod_tests
@@ -3,9 +3,9 @@
 
 t_Log "Running $0"
 
-# Check that the testgroup exists with GID 1010
-grep -q "testgroup:x:1010:testshadow" /etc/group || { t_Log "FAIL Test group doesn't exist"; exit $FAIL; }
+# Check that the testgroup exists with GID 2010
+grep -q "testgroup:x:2010:testshadow" /etc/group || { t_Log "FAIL Test group doesn't exist"; exit $FAIL; }
 
-echo "Changing GID for group testgroup to 1011"
-groupmod -g 1011 testgroup
+echo "Changing GID for group testgroup to 2011"
+groupmod -g 2011 testgroup
 t_CheckExitStatus $?
